version: '2.4'

services:
  nginx-proxy-redirect:
    build: .
    environment:
      CLIENT_MAX_BODY_SIZE: 10m
      WORKER_PROCESSES: 1
    image: interaction/nginx-proxy-redirect:local
    volumes:
      - .:/opt/nginx-proxy-redirect
